[build]
  publish   = "."
  functions = "netlify/functions"

[functions]
  node_bundler  = "esbuild"
  included_files = [
    "template.pdf",
    "malgun.ttf",
    "netlify/functions/mappings/**"
  ]
